version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    expose:
      - 5432
    volumes:
      - {ADD_PATH_TO_VOLUME_HERE}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD={ADD_DB_PASSWORD_HERE}
      - POSTGRES_USER={ADD_DB_USER_HERE}
      - POSTGRES_DB=postgres
  manager:
    image: tournament-manager:latest
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY={ADD_SECRET_KEY_HERE}
      - BOT_TOKEN={ADD_TELEGRAM_BOT_TOKEN_HERE}
      - DB_USER={ADD_DB_USER_HERE}
      - DB_PASSWORD={ADD_DB_PASSWORD_HERE}
      - DB_HOST=postgres
      - DB_PORT=5432
      - PYTHONPATH=$PYTHONPATH:/app
